"""ImAnim animation bindings"""

from typing import overload, Any


IMANIM_VERSION: str = '1.0.0'

IMANIM_VERSION_NUM: int = 10000

EASE_LINEAR: int = 0

EASE_IN_QUAD: int = 1

EASE_OUT_QUAD: int = 2

EASE_IN_OUT_QUAD: int = 3

EASE_IN_CUBIC: int = 4

EASE_OUT_CUBIC: int = 5

EASE_IN_OUT_CUBIC: int = 6

EASE_IN_QUART: int = 7

EASE_OUT_QUART: int = 8

EASE_IN_OUT_QUART: int = 9

EASE_IN_QUINT: int = 10

EASE_OUT_QUINT: int = 11

EASE_IN_OUT_QUINT: int = 12

EASE_IN_SINE: int = 13

EASE_OUT_SINE: int = 14

EASE_IN_OUT_SINE: int = 15

EASE_IN_EXPO: int = 16

EASE_OUT_EXPO: int = 17

EASE_IN_OUT_EXPO: int = 18

EASE_IN_CIRC: int = 19

EASE_OUT_CIRC: int = 20

EASE_IN_OUT_CIRC: int = 21

EASE_IN_BACK: int = 22

EASE_OUT_BACK: int = 23

EASE_IN_OUT_BACK: int = 24

EASE_IN_ELASTIC: int = 25

EASE_OUT_ELASTIC: int = 26

EASE_IN_OUT_ELASTIC: int = 27

EASE_IN_BOUNCE: int = 28

EASE_OUT_BOUNCE: int = 29

EASE_IN_OUT_BOUNCE: int = 30

EASE_STEPS: int = 31

EASE_CUBIC_BEZIER: int = 32

EASE_SPRING: int = 33

POLICY_CROSSFADE: int = 0

POLICY_CUT: int = 1

POLICY_QUEUE: int = 2

COLOR_SRGB: int = 0

COLOR_SRGB_LINEAR: int = 1

COLOR_HSV: int = 2

COLOR_OKLAB: int = 3

COLOR_OKLCH: int = 4

ANCHOR_WINDOW_CONTENT: int = 0

ANCHOR_WINDOW: int = 1

ANCHOR_VIEWPORT: int = 2

ANCHOR_LAST_ITEM: int = 3

WAVE_SINE: int = 0

WAVE_TRIANGLE: int = 1

WAVE_SAWTOOTH: int = 2

WAVE_SQUARE: int = 3

ROTATION_SHORTEST: int = 0

ROTATION_LONGEST: int = 1

ROTATION_CW: int = 2

ROTATION_CCW: int = 3

ROTATION_DIRECT: int = 4

DIRECTION_NORMAL: int = 0

DIRECTION_REVERSE: int = 1

DIRECTION_ALTERNATE: int = 2

class EaseDesc:
    def __init__(self) -> None: ...

    @property
    def type(self) -> int: ...

    @type.setter
    def type(self, arg: int, /) -> None: ...

    @property
    def p0(self) -> float: ...

    @p0.setter
    def p0(self, arg: float, /) -> None: ...

    @property
    def p1(self) -> float: ...

    @p1.setter
    def p1(self, arg: float, /) -> None: ...

    @property
    def p2(self) -> float: ...

    @p2.setter
    def p2(self, arg: float, /) -> None: ...

    @property
    def p3(self) -> float: ...

    @p3.setter
    def p3(self, arg: float, /) -> None: ...

class EasePerAxis:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: EaseDesc, /) -> None: ...

    @overload
    def __init__(self, arg0: EaseDesc, arg1: EaseDesc, /) -> None: ...

    @overload
    def __init__(self, arg0: EaseDesc, arg1: EaseDesc, arg2: EaseDesc, arg3: EaseDesc, /) -> None: ...

    @property
    def x(self) -> EaseDesc: ...

    @x.setter
    def x(self, arg: EaseDesc, /) -> None: ...

    @property
    def y(self) -> EaseDesc: ...

    @y.setter
    def y(self, arg: EaseDesc, /) -> None: ...

    @property
    def z(self) -> EaseDesc: ...

    @z.setter
    def z(self, arg: EaseDesc, /) -> None: ...

    @property
    def w(self) -> EaseDesc: ...

    @w.setter
    def w(self, arg: EaseDesc, /) -> None: ...

class SpringParams:
    def __init__(self) -> None: ...

    @property
    def mass(self) -> float: ...

    @mass.setter
    def mass(self, arg: float, /) -> None: ...

    @property
    def stiffness(self) -> float: ...

    @stiffness.setter
    def stiffness(self, arg: float, /) -> None: ...

    @property
    def damping(self) -> float: ...

    @damping.setter
    def damping(self, arg: float, /) -> None: ...

    @property
    def initial_velocity(self) -> float: ...

    @initial_velocity.setter
    def initial_velocity(self, arg: float, /) -> None: ...

class MorphOptions:
    def __init__(self) -> None: ...

    @property
    def samples(self) -> int: ...

    @samples.setter
    def samples(self, arg: int, /) -> None: ...

    @property
    def match_endpoints(self) -> bool: ...

    @match_endpoints.setter
    def match_endpoints(self, arg: bool, /) -> None: ...

    @property
    def use_arc_length(self) -> bool: ...

    @use_arc_length.setter
    def use_arc_length(self, arg: bool, /) -> None: ...

class Gradient:
    def __init__(self) -> None: ...

    def add(self, position: float, color: tuple[float, float, float, float]) -> Gradient: ...

    def sample(self, t: float, color_space: int = 3) -> tuple[float, float, float, float]: ...

    @property
    def stop_count(self) -> int: ...

    @staticmethod
    def solid(color: tuple[float, float, float, float]) -> Gradient: ...

    @staticmethod
    def two_color(start: tuple[float, float, float, float], end: tuple[float, float, float, float]) -> Gradient: ...

    @staticmethod
    def three_color(start: tuple[float, float, float, float], mid: tuple[float, float, float, float], end: tuple[float, float, float, float]) -> Gradient: ...

class Transform:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, position: tuple[float, float], rotation: float = 0.0, scale: tuple[float, float] = (1.0, 1.0)) -> None: ...

    @property
    def position(self) -> tuple[float, float]: ...

    @position.setter
    def position(self, arg: tuple[float, float], /) -> None: ...

    @property
    def scale(self) -> tuple[float, float]: ...

    @scale.setter
    def scale(self, arg: tuple[float, float], /) -> None: ...

    @property
    def rotation(self) -> float: ...

    @rotation.setter
    def rotation(self, arg: float, /) -> None: ...

    @staticmethod
    def identity() -> Transform: ...

    def combine(self, other: Transform) -> Transform: ...

    def apply(self, point: tuple[float, float]) -> tuple[float, float]: ...

    def inverse(self) -> Transform: ...

class Path:
    @staticmethod
    def begin(path_id: int, start: tuple[float, float]) -> Path: ...

    def line_to(self, end: tuple[float, float]) -> Path: ...

    def quadratic_to(self, ctrl: tuple[float, float], end: tuple[float, float]) -> Path: ...

    def cubic_to(self, ctrl1: tuple[float, float], ctrl2: tuple[float, float], end: tuple[float, float]) -> Path: ...

    def catmull_to(self, end: tuple[float, float], tension: float = 0.5) -> Path: ...

    def close(self) -> Path: ...

    def end(self) -> None: ...

    @property
    def id(self) -> int: ...

class Clip:
    @staticmethod
    def begin(clip_id: int) -> Clip: ...

    def key_float(self, channel: int, time: float, value: float, ease_type: int = 0) -> Clip: ...

    def key_vec2(self, channel: int, time: float, value: tuple[float, float], ease_type: int = 0) -> Clip: ...

    def key_vec4(self, channel: int, time: float, value: tuple[float, float, float, float], ease_type: int = 0) -> Clip: ...

    def key_int(self, channel: int, time: float, value: int, ease_type: int = 0) -> Clip: ...

    def key_color(self, channel: int, time: float, value: tuple[float, float, float, float], color_space: int = 3, ease_type: int = 0) -> Clip: ...

    def key_float_spring(self, channel: int, time: float, target: float, spring: SpringParams) -> Clip: ...

    def seq_begin(self) -> Clip: ...

    def seq_end(self) -> Clip: ...

    def par_begin(self) -> Clip: ...

    def par_end(self) -> Clip: ...

    def set_loop(self, loop: bool, direction: int = 0, loop_count: int = -1) -> Clip: ...

    def set_delay(self, delay_seconds: float) -> Clip: ...

    def set_stagger(self, count: int, each_delay: float, from_center_bias: float = 0.0) -> Clip: ...

    def end(self) -> None: ...

    @property
    def id(self) -> int: ...

class Instance:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, instance_id: int) -> None: ...

    def pause(self) -> None: ...

    def resume(self) -> None: ...

    def stop(self) -> None: ...

    def destroy(self) -> None: ...

    def seek(self, time: float) -> None: ...

    def set_time_scale(self, scale: float) -> None: ...

    def set_weight(self, weight: float) -> None: ...

    @overload
    def then(self, next_clip_id: int) -> Instance: ...

    @overload
    def then(self, next_clip_id: int, next_instance_id: int) -> Instance: ...

    def then_delay(self, delay: float) -> Instance: ...

    @property
    def time(self) -> float: ...

    @property
    def duration(self) -> float: ...

    @property
    def is_playing(self) -> bool: ...

    @property
    def is_paused(self) -> bool: ...

    @property
    def valid(self) -> bool: ...

    @property
    def id(self) -> int: ...

    def get_float(self, channel: int) -> float | None: ...

    def get_vec2(self, channel: int) -> tuple[float, float] | None: ...

    def get_vec4(self, channel: int) -> tuple[float, float, float, float] | None: ...

    def get_int(self, channel: int) -> int | None: ...

    def get_color(self, channel: int, color_space: int = 3) -> tuple[float, float, float, float] | None: ...

def hash_str(value: str, seed: int = 0) -> int:
    """Return the same hash primitive used by ImGui/ImAnim IDs."""

def update_begin_frame() -> None: ...

def gc(max_age_frames: int = 600) -> None: ...

def pool_clear() -> None: ...

def reserve(cap_float: int, cap_vec2: int, cap_vec4: int, cap_int: int, cap_color: int) -> None: ...

def set_ease_lut_samples(count: int) -> None: ...

def set_global_time_scale(scale: float) -> None: ...

def get_global_time_scale() -> float: ...

def set_lazy_init(enable: bool) -> None: ...

def is_lazy_init_enabled() -> bool: ...

def eval_preset(type: int, t: float) -> float: ...

def ease_preset(type: int) -> EaseDesc: ...

def ease_bezier(x1: float, y1: float, x2: float, y2: float) -> EaseDesc: ...

def ease_steps(steps: int, mode: int) -> EaseDesc: ...

def ease_back(overshoot: float) -> EaseDesc: ...

def ease_elastic(amplitude: float, period: float) -> EaseDesc: ...

def ease_spring(mass: float, stiffness: float, damping: float, initial_velocity: float) -> EaseDesc: ...

def bezier_quadratic(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], t: float) -> tuple[float, float]: ...

def bezier_cubic(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], p3: tuple[float, float], t: float) -> tuple[float, float]: ...

def catmull_rom(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], p3: tuple[float, float], t: float, tension: float = 0.5) -> tuple[float, float]: ...

def bezier_quadratic_deriv(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], t: float) -> tuple[float, float]: ...

def bezier_cubic_deriv(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], p3: tuple[float, float], t: float) -> tuple[float, float]: ...

def catmull_rom_deriv(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], p3: tuple[float, float], t: float, tension: float = 0.5) -> tuple[float, float]: ...

def get_blended_color(a_srgb: tuple[float, float, float, float], b_srgb: tuple[float, float, float, float], t: float, color_space: int = 3) -> tuple[float, float, float, float]: ...

def tween_float(id: int, channel_id: int, target: float, duration: float, ease: EaseDesc, policy: int, dt: float, init_value: float = 0.0) -> float: ...

def tween_vec2(id: int, channel_id: int, target: tuple[float, float], duration: float, ease: EaseDesc, policy: int, dt: float, init_value: tuple[float, float] = (0.0, 0.0)) -> tuple[float, float]: ...

def tween_vec4(id: int, channel_id: int, target: tuple[float, float, float, float], duration: float, ease: EaseDesc, policy: int, dt: float, init_value: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)) -> tuple[float, float, float, float]: ...

def tween_int(id: int, channel_id: int, target: int, duration: float, ease: EaseDesc, policy: int, dt: float, init_value: int = 0) -> int: ...

def tween_color(id: int, channel_id: int, target_srgb: tuple[float, float, float, float], duration: float, ease: EaseDesc, policy: int, color_space: int, dt: float, init_value: tuple[float, float, float, float] = (1.0, 1.0, 1.0, 1.0)) -> tuple[float, float, float, float]: ...

def tween_vec2_per_axis(id: int, channel_id: int, target: tuple[float, float], duration: float, ease: EasePerAxis, policy: int, dt: float) -> tuple[float, float]: ...

def tween_vec4_per_axis(id: int, channel_id: int, target: tuple[float, float, float, float], duration: float, ease: EasePerAxis, policy: int, dt: float) -> tuple[float, float, float, float]: ...

def tween_color_per_axis(id: int, channel_id: int, target_srgb: tuple[float, float, float, float], duration: float, ease: EasePerAxis, policy: int, color_space: int, dt: float) -> tuple[float, float, float, float]: ...

def tween_float_rel(id: int, channel_id: int, percent: float, px_bias: float, duration: float, ease: EaseDesc, policy: int, anchor_space: int, axis: int, dt: float) -> float: ...

def tween_vec2_rel(id: int, channel_id: int, percent: tuple[float, float], px_bias: tuple[float, float], duration: float, ease: EaseDesc, policy: int, anchor_space: int, dt: float) -> tuple[float, float]: ...

def tween_vec4_rel(id: int, channel_id: int, percent: tuple[float, float, float, float], px_bias: tuple[float, float, float, float], duration: float, ease: EaseDesc, policy: int, anchor_space: int, dt: float) -> tuple[float, float, float, float]: ...

def tween_color_rel(id: int, channel_id: int, percent: tuple[float, float, float, float], px_bias: tuple[float, float, float, float], duration: float, ease: EaseDesc, policy: int, color_space: int, anchor_space: int, dt: float) -> tuple[float, float, float, float]: ...

def anchor_size(space: int) -> tuple[float, float]: ...

def rebase_float(id: int, channel_id: int, new_target: float, dt: float) -> None: ...

def rebase_vec2(id: int, channel_id: int, new_target: tuple[float, float], dt: float) -> None: ...

def rebase_vec4(id: int, channel_id: int, new_target: tuple[float, float, float, float], dt: float) -> None: ...

def rebase_color(id: int, channel_id: int, new_target: tuple[float, float, float, float], dt: float) -> None: ...

def rebase_int(id: int, channel_id: int, new_target: int, dt: float) -> None: ...

def oscillate(id: int, amplitude: float, frequency: float, wave_type: int, phase: float, dt: float) -> float: ...

def oscillate_int(id: int, amplitude: int, frequency: float, wave_type: int, phase: float, dt: float) -> int: ...

def oscillate_vec2(id: int, amplitude: tuple[float, float], frequency: tuple[float, float], wave_type: int, phase: tuple[float, float], dt: float) -> tuple[float, float]: ...

def oscillate_vec4(id: int, amplitude: tuple[float, float, float, float], frequency: tuple[float, float, float, float], wave_type: int, phase: tuple[float, float, float, float], dt: float) -> tuple[float, float, float, float]: ...

def oscillate_color(id: int, base_color: tuple[float, float, float, float], amplitude: tuple[float, float, float, float], frequency: float, wave_type: int, phase: float, color_space: int, dt: float) -> tuple[float, float, float, float]: ...

def shake(id: int, intensity: float, frequency: float, decay_time: float, dt: float) -> float: ...

def shake_vec2(id: int, intensity: tuple[float, float], frequency: float, decay_time: float, dt: float) -> tuple[float, float]: ...

def shake_vec4(id: int, intensity: tuple[float, float, float, float], frequency: float, decay_time: float, dt: float) -> tuple[float, float, float, float]: ...

def wiggle(id: int, amplitude: float, frequency: float, dt: float) -> float: ...

def wiggle_vec2(id: int, amplitude: tuple[float, float], frequency: float, dt: float) -> tuple[float, float]: ...

def wiggle_vec4(id: int, amplitude: tuple[float, float, float, float], frequency: float, dt: float) -> tuple[float, float, float, float]: ...

def trigger_shake(id: int) -> None: ...

def path_exists(path_id: int) -> bool: ...

def path_length(path_id: int) -> float: ...

def path_evaluate(path_id: int, t: float) -> tuple[float, float]: ...

def path_tangent(path_id: int, t: float) -> tuple[float, float]: ...

def path_angle(path_id: int, t: float) -> float: ...

def path_build_arc_lut(path_id: int, subdivisions: int = 64) -> None: ...

def path_has_arc_lut(path_id: int) -> bool: ...

def path_distance_to_t(path_id: int, distance: float) -> float: ...

def path_evaluate_at_distance(path_id: int, distance: float) -> tuple[float, float]: ...

def path_angle_at_distance(path_id: int, distance: float) -> float: ...

def path_tangent_at_distance(path_id: int, distance: float) -> tuple[float, float]: ...

def path_morph(path_a: int, path_b: int, t: float, blend: float, opts: MorphOptions = ...) -> tuple[float, float]: ...

def path_morph_tangent(path_a: int, path_b: int, t: float, blend: float, opts: MorphOptions = ...) -> tuple[float, float]: ...

def path_morph_angle(path_a: int, path_b: int, t: float, blend: float, opts: MorphOptions = ...) -> float: ...

def tween_path(id: int, channel_id: int, path_id: int, duration: float, ease: EaseDesc, policy: int, dt: float) -> tuple[float, float]: ...

def tween_path_angle(id: int, channel_id: int, path_id: int, duration: float, ease: EaseDesc, policy: int, dt: float) -> float: ...

def tween_path_morph(id: int, channel_id: int, path_a: int, path_b: int, target_blend: float, duration: float, path_ease: EaseDesc, morph_ease: EaseDesc, policy: int, dt: float, opts: MorphOptions = ...) -> tuple[float, float]: ...

def get_morph_blend(id: int, channel_id: int) -> float: ...

def gradient_lerp(a: Gradient, b: Gradient, t: float, color_space: int = 3) -> Gradient: ...

def tween_gradient(id: int, channel_id: int, target: Gradient, duration: float, ease: EaseDesc, policy: int, color_space: int, dt: float) -> Gradient: ...

def transform_lerp(a: Transform, b: Transform, t: float, rotation_mode: int = 0) -> Transform: ...

def tween_transform(id: int, channel_id: int, target: Transform, duration: float, ease: EaseDesc, policy: int, rotation_mode: int, dt: float) -> Transform: ...

def transform_from_matrix(m00: float, m01: float, m10: float, m11: float, tx: float, ty: float) -> Transform: ...

def transform_to_matrix(transform: Transform) -> list[float]: ...

def clip_init(initial_clip_cap: int = 256, initial_inst_cap: int = 4096) -> None: ...

def clip_shutdown() -> None: ...

def clip_update(dt: float) -> None: ...

def clip_gc(max_age_frames: int = 600) -> None: ...

def play(clip_id: int, instance_id: int) -> Instance: ...

def get_instance(instance_id: int) -> Instance: ...

def clip_duration(clip_id: int) -> float: ...

def clip_exists(clip_id: int) -> bool: ...

def stagger_delay(clip_id: int, index: int) -> float: ...

def play_stagger(clip_id: int, instance_id: int, index: int) -> Instance: ...

def layer_begin(instance_id: int) -> None: ...

def layer_add(instance: Instance, weight: float) -> None: ...

def layer_end(instance_id: int) -> None: ...

def get_blended_float(instance_id: int, channel: int) -> float | None: ...

def get_blended_vec2(instance_id: int, channel: int) -> tuple[float, float] | None: ...

def get_blended_vec4(instance_id: int, channel: int) -> tuple[float, float, float, float] | None: ...

def get_blended_int(instance_id: int, channel: int) -> int | None: ...
